ci: fix gcr container tag casing
This commit fixes the casing of container tags pushed to gcr.io, which
requires that repository names be lowercase:

```sh
ERROR: invalid tag "ghcr.io/krumIO/ui-extension-krum-rancher-extensions-demo:0.1.0": repository name must be lowercase
```